# Base file, do not modifiy.
# Make changes in docker-compose.override.yml instead.
# See https://docs.docker.com/compose/extends/#example-use-case
version: '3.3'
services:

  mysql:
    image: mysql:8.0.29
    platform: linux/amd64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=500
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-healthcheck.sh:/healthcheck.sh
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lisk
      MYSQL_USER: lisk
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: [ 'CMD', 'bash', '/healthcheck.sh' ]
      interval: 1m
      timeout: 5s

volumes:
  db-data:
